// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SWD.DAL.Models;

#nullable disable

namespace SWD.DAL.Migrations
{
    [DbContext(typeof(IoTFinalDbContext))]
    [Migration("20260125031748_AddSystemLogColumns")]
    partial class AddSystemLogColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SWD.DAL.Models.AlertHistory", b =>
                {
                    b.Property<long>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("HistoryID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("HistoryId"));

                    b.Property<string>("Message")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp");

                    b.Property<int>("RuleId")
                        .HasColumnType("integer")
                        .HasColumnName("RuleID");

                    b.Property<int>("SensorId")
                        .HasColumnType("integer")
                        .HasColumnName("SensorID");

                    b.Property<string>("Severity")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("TriggeredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("NOW()");

                    b.Property<double?>("ValueAtTrigger")
                        .HasColumnType("double precision");

                    b.HasKey("HistoryId");

                    b.HasIndex("RuleId");

                    b.HasIndex("SensorId");

                    b.ToTable("AlertHistory", (string)null);
                });

            modelBuilder.Entity("SWD.DAL.Models.AlertRule", b =>
                {
                    b.Property<int>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("RuleID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RuleId"));

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<double?>("MaxVal")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinVal")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NotificationMethod")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Priority")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SensorId")
                        .HasColumnType("integer")
                        .HasColumnName("SensorID");

                    b.HasKey("RuleId");

                    b.HasIndex("SensorId");

                    b.ToTable("AlertRule", (string)null);
                });

            modelBuilder.Entity("SWD.DAL.Models.Hub", b =>
                {
                    b.Property<int>("HubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("HubID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HubId"));

                    b.Property<bool?>("IsOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastHandshake")
                        .HasColumnType("timestamp");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("SiteID");

                    b.HasKey("HubId");

                    b.HasIndex("SiteId");

                    b.HasIndex(new[] { "MacAddress" }, "UQ__Hub__MacAddress")
                        .IsUnique();

                    b.ToTable("Hub", (string)null);
                });

            modelBuilder.Entity("SWD.DAL.Models.Notification", b =>
                {
                    b.Property<long>("NotiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("NotiID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("NotiId"));

                    b.Property<long>("HistoryId")
                        .HasColumnType("bigint")
                        .HasColumnName("HistoryID");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UserID");

                    b.HasKey("NotiId");

                    b.HasIndex("HistoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("SWD.DAL.Models.Organization", b =>
                {
                    b.Property<int>("OrgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("OrgID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrgId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("OrgId");

                    b.ToTable("Organization", (string)null);
                });

            modelBuilder.Entity("SWD.DAL.Models.Reading", b =>
                {
                    b.Property<long>("ReadingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("ReadingID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ReadingId"));

                    b.Property<DateTime?>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6)
                        .HasColumnType("timestamp(6) with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("SensorId")
                        .HasColumnType("integer")
                        .HasColumnName("SensorID");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("ReadingId");

                    b.HasIndex(new[] { "SensorId", "RecordedAt" }, "IDX_Reading_Sensor_Time");

                    b.ToTable("Reading", (string)null);
                });

            modelBuilder.Entity("SWD.DAL.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("RoleID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RoleId");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Role__RoleName")
                        .IsUnique();

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("SWD.DAL.Models.Sensor", b =>
                {
                    b.Property<int>("SensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("SensorID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SensorId"));

                    b.Property<double?>("CurrentValue")
                        .HasColumnType("double precision");

                    b.Property<int>("HubId")
                        .HasColumnType("integer")
                        .HasColumnName("HubID");

                    b.Property<DateTime?>("LastUpdate")
                        .HasPrecision(6)
                        .HasColumnType("timestamp(6) with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("TypeID");

                    b.HasKey("SensorId");

                    b.HasIndex("HubId");

                    b.HasIndex("TypeId");

                    b.ToTable("Sensor", (string)null);
                });

            modelBuilder.Entity("SWD.DAL.Models.SensorType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("TypeID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("TypeId");

                    b.ToTable("SensorType", (string)null);
                });

            modelBuilder.Entity("SWD.DAL.Models.Site", b =>
                {
                    b.Property<int>("SiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("SiteID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SiteId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("GeoLocation")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OrgId")
                        .HasColumnType("integer")
                        .HasColumnName("OrgID");

                    b.HasKey("SiteId");

                    b.HasIndex("OrgId");

                    b.ToTable("Site", (string)null);
                });

            modelBuilder.Entity("SWD.DAL.Models.SystemLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("LogID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LogId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("RawPayload")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("EOH-Webhook");

                    b.HasKey("LogId");

                    b.ToTable("SystemLog", (string)null);
                });

            modelBuilder.Entity("SWD.DAL.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("UserID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("OrgId")
                        .HasColumnType("integer")
                        .HasColumnName("OrgID");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int?>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("SiteID");

                    b.HasKey("UserId");

                    b.HasIndex("OrgId");

                    b.HasIndex("RoleId");

                    b.HasIndex("SiteId");

                    b.HasIndex(new[] { "Email" }, "UQ__User__Email")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("SWD.DAL.Models.AlertHistory", b =>
                {
                    b.HasOne("SWD.DAL.Models.AlertRule", "Rule")
                        .WithMany("AlertHistories")
                        .HasForeignKey("RuleId")
                        .IsRequired();

                    b.HasOne("SWD.DAL.Models.Sensor", "Sensor")
                        .WithMany("AlertHistories")
                        .HasForeignKey("SensorId")
                        .IsRequired();

                    b.Navigation("Rule");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("SWD.DAL.Models.AlertRule", b =>
                {
                    b.HasOne("SWD.DAL.Models.Sensor", "Sensor")
                        .WithMany("AlertRules")
                        .HasForeignKey("SensorId")
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("SWD.DAL.Models.Hub", b =>
                {
                    b.HasOne("SWD.DAL.Models.Site", "Site")
                        .WithMany("Hubs")
                        .HasForeignKey("SiteId")
                        .IsRequired();

                    b.Navigation("Site");
                });

            modelBuilder.Entity("SWD.DAL.Models.Notification", b =>
                {
                    b.HasOne("SWD.DAL.Models.AlertHistory", "History")
                        .WithMany("Notifications")
                        .HasForeignKey("HistoryId")
                        .IsRequired();

                    b.HasOne("SWD.DAL.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("History");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWD.DAL.Models.Reading", b =>
                {
                    b.HasOne("SWD.DAL.Models.Sensor", "Sensor")
                        .WithMany("Readings")
                        .HasForeignKey("SensorId")
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("SWD.DAL.Models.Sensor", b =>
                {
                    b.HasOne("SWD.DAL.Models.Hub", "Hub")
                        .WithMany("Sensors")
                        .HasForeignKey("HubId")
                        .IsRequired();

                    b.HasOne("SWD.DAL.Models.SensorType", "Type")
                        .WithMany("Sensors")
                        .HasForeignKey("TypeId")
                        .IsRequired();

                    b.Navigation("Hub");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("SWD.DAL.Models.Site", b =>
                {
                    b.HasOne("SWD.DAL.Models.Organization", "Org")
                        .WithMany("Sites")
                        .HasForeignKey("OrgId")
                        .IsRequired();

                    b.Navigation("Org");
                });

            modelBuilder.Entity("SWD.DAL.Models.User", b =>
                {
                    b.HasOne("SWD.DAL.Models.Organization", "Org")
                        .WithMany("Users")
                        .HasForeignKey("OrgId")
                        .IsRequired();

                    b.HasOne("SWD.DAL.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired();

                    b.HasOne("SWD.DAL.Models.Site", "Site")
                        .WithMany("Users")
                        .HasForeignKey("SiteId");

                    b.Navigation("Org");

                    b.Navigation("Role");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("SWD.DAL.Models.AlertHistory", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("SWD.DAL.Models.AlertRule", b =>
                {
                    b.Navigation("AlertHistories");
                });

            modelBuilder.Entity("SWD.DAL.Models.Hub", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("SWD.DAL.Models.Organization", b =>
                {
                    b.Navigation("Sites");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SWD.DAL.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SWD.DAL.Models.Sensor", b =>
                {
                    b.Navigation("AlertHistories");

                    b.Navigation("AlertRules");

                    b.Navigation("Readings");
                });

            modelBuilder.Entity("SWD.DAL.Models.SensorType", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("SWD.DAL.Models.Site", b =>
                {
                    b.Navigation("Hubs");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SWD.DAL.Models.User", b =>
                {
                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
