// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SWD.DAL.Models;

#nullable disable

namespace SWD.DAL.Migrations
{
    [DbContext(typeof(IoTFinalDbContext))]
    partial class IoTFinalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SWD.DAL.Models.AlertRule", b =>
                {
                    b.Property<int>("RuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("RuleID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RuleId"));

                    b.Property<string>("ConditionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<double?>("MaxVal")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinVal")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NotificationMethod")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Priority")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SensorId")
                        .HasColumnType("integer")
                        .HasColumnName("SensorID");

                    b.HasKey("RuleId")
                        .HasName("PK__AlertRul__110458C20C3B9D6E");

                    b.HasIndex("SensorId");

                    b.ToTable("AlertRule", (string)null);
                });

            modelBuilder.Entity("SWD.DAL.Models.Hub", b =>
                {
                    b.Property<int>("HubId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("HubID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HubId"));

                    b.Property<bool?>("IsOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastHandshake")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("SiteID");

                    b.HasKey("HubId")
                        .HasName("PK__Hub__9F4FFECFC0EB50EB");

                    b.HasIndex("SiteId");

                    b.HasIndex(new[] { "MacAddress" }, "UQ__Hub__50EDF1CDFDF0BE28")
                        .IsUnique();

                    b.ToTable("Hub", (string)null);
                });

            modelBuilder.Entity("SWD.DAL.Models.Notification", b =>
                {
                    b.Property<long>("NotiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("NotiID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("NotiId"));

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RuleId")
                        .HasColumnType("integer")
                        .HasColumnName("RuleID");

                    b.Property<DateTime?>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("UserID");

                    b.HasKey("NotiId")
                        .HasName("PK__Notifica__EDC08EF20E2D3E48");

                    b.HasIndex("RuleId");

                    b.HasIndex("UserId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("SWD.DAL.Models.Organization", b =>
                {
                    b.Property<int>("OrgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("OrgID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrgId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("OrgId")
                        .HasName("PK__Organiza__420C9E0C845179E3");

                    b.ToTable("Organization", (string)null);
                });

            modelBuilder.Entity("SWD.DAL.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("RoleID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Role__8AFACE3A10B7CB9B");

                    b.HasIndex(new[] { "RoleName" }, "UQ__Role__8A2B6160395B11F5")
                        .IsUnique();

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("SWD.DAL.Models.Sensor", b =>
                {
                    b.Property<int>("SensorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("SensorID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SensorId"));

                    b.Property<int>("HubId")
                        .HasColumnType("integer")
                        .HasColumnName("HubID");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active");

                    b.Property<int>("TypeId")
                        .HasColumnType("integer")
                        .HasColumnName("TypeID");

                    b.HasKey("SensorId")
                        .HasName("PK__Sensor__D809841AFEF09FD0");

                    b.HasIndex("HubId");

                    b.HasIndex("TypeId");

                    b.ToTable("Sensor", (string)null);
                });

            modelBuilder.Entity("SWD.DAL.Models.SensorData", b =>
                {
                    b.Property<long>("DataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("DataID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("DataId"));

                    b.Property<int>("HubId")
                        .HasColumnType("integer")
                        .HasColumnName("HubID");

                    b.Property<DateTime?>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("timestamp(3) with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("SensorId")
                        .HasColumnType("integer")
                        .HasColumnName("SensorID");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("DataId")
                        .HasName("PK__SensorDa__C80F9C6E561FFF59");

                    b.HasIndex("HubId");

                    b.HasIndex(new[] { "SensorId", "RecordedAt" }, "IDX_SensorData_Sensor_Time");

                    b.ToTable("SensorData", (string)null);
                });

            modelBuilder.Entity("SWD.DAL.Models.SensorType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("TypeID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TypeId"));

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("TypeId")
                        .HasName("PK__SensorTy__516F0395C1AE3D64");

                    b.ToTable("SensorType", (string)null);
                });

            modelBuilder.Entity("SWD.DAL.Models.Site", b =>
                {
                    b.Property<int>("SiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("SiteID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SiteId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("GeoLocation")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OrgId")
                        .HasColumnType("integer")
                        .HasColumnName("OrgID");

                    b.HasKey("SiteId")
                        .HasName("PK__Site__B9DCB9032CBAC039");

                    b.HasIndex("OrgId");

                    b.ToTable("Site", (string)null);
                });

            modelBuilder.Entity("SWD.DAL.Models.SystemLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("LogID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("LogId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("RawPayload")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("EOH-Webhook");

                    b.HasKey("LogId")
                        .HasName("PK__SystemLo__5E5499A8547BC738");

                    b.ToTable("SystemLog", (string)null);
                });

            modelBuilder.Entity("SWD.DAL.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("UserID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("OrgId")
                        .HasColumnType("integer")
                        .HasColumnName("OrgID");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int?>("SiteId")
                        .HasColumnType("integer")
                        .HasColumnName("SiteID");

                    b.HasKey("UserId")
                        .HasName("PK__User__1788CCACE687B793");

                    b.HasIndex("OrgId");

                    b.HasIndex("RoleId");

                    b.HasIndex("SiteId");

                    b.HasIndex(new[] { "Email" }, "UQ__User__A9D105342B2B253F")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("SWD.DAL.Models.AlertRule", b =>
                {
                    b.HasOne("SWD.DAL.Models.Sensor", "Sensor")
                        .WithMany("AlertRules")
                        .HasForeignKey("SensorId")
                        .IsRequired()
                        .HasConstraintName("FK__AlertRule__Senso__571DF1D5");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("SWD.DAL.Models.Hub", b =>
                {
                    b.HasOne("SWD.DAL.Models.Site", "Site")
                        .WithMany("Hubs")
                        .HasForeignKey("SiteId")
                        .IsRequired()
                        .HasConstraintName("FK__Hub__SiteID__3F466844");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("SWD.DAL.Models.Notification", b =>
                {
                    b.HasOne("SWD.DAL.Models.AlertRule", "Rule")
                        .WithMany("Notifications")
                        .HasForeignKey("RuleId")
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__RuleID__60A75C0F");

                    b.HasOne("SWD.DAL.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__UserI__619B8048");

                    b.Navigation("Rule");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SWD.DAL.Models.Sensor", b =>
                {
                    b.HasOne("SWD.DAL.Models.Hub", "Hub")
                        .WithMany("Sensors")
                        .HasForeignKey("HubId")
                        .IsRequired()
                        .HasConstraintName("FK__Sensor__HubID__44FF419A");

                    b.HasOne("SWD.DAL.Models.SensorType", "Type")
                        .WithMany("Sensors")
                        .HasForeignKey("TypeId")
                        .IsRequired()
                        .HasConstraintName("FK__Sensor__TypeID__45F365D3");

                    b.Navigation("Hub");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("SWD.DAL.Models.SensorData", b =>
                {
                    b.HasOne("SWD.DAL.Models.Hub", "Hub")
                        .WithMany("SensorDatas")
                        .HasForeignKey("HubId")
                        .IsRequired()
                        .HasConstraintName("FK__SensorData__HubID__HubData");

                    b.HasOne("SWD.DAL.Models.Sensor", "Sensor")
                        .WithMany("SensorDatas")
                        .HasForeignKey("SensorId")
                        .IsRequired()
                        .HasConstraintName("FK__SensorData__SensorI__49C3F6B7");

                    b.Navigation("Hub");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("SWD.DAL.Models.Site", b =>
                {
                    b.HasOne("SWD.DAL.Models.Organization", "Org")
                        .WithMany("Sites")
                        .HasForeignKey("OrgId")
                        .IsRequired()
                        .HasConstraintName("FK__Site__OrgID__3A81B327");

                    b.Navigation("Org");
                });

            modelBuilder.Entity("SWD.DAL.Models.User", b =>
                {
                    b.HasOne("SWD.DAL.Models.Organization", "Org")
                        .WithMany("Users")
                        .HasForeignKey("OrgId")
                        .IsRequired()
                        .HasConstraintName("FK__User__OrgID__5165187F");

                    b.HasOne("SWD.DAL.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("FK__User__RoleId__534D60F1");

                    b.HasOne("SWD.DAL.Models.Site", "Site")
                        .WithMany("Users")
                        .HasForeignKey("SiteId")
                        .HasConstraintName("FK__User__SiteID__52593CB8");

                    b.Navigation("Org");

                    b.Navigation("Role");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("SWD.DAL.Models.AlertRule", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("SWD.DAL.Models.Hub", b =>
                {
                    b.Navigation("SensorDatas");

                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("SWD.DAL.Models.Organization", b =>
                {
                    b.Navigation("Sites");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SWD.DAL.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SWD.DAL.Models.Sensor", b =>
                {
                    b.Navigation("AlertRules");

                    b.Navigation("SensorDatas");
                });

            modelBuilder.Entity("SWD.DAL.Models.SensorType", b =>
                {
                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("SWD.DAL.Models.Site", b =>
                {
                    b.Navigation("Hubs");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SWD.DAL.Models.User", b =>
                {
                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
